services:
    symfony:
        build:
            context: .
        ports:
            - '8000:80'
        volumes:
            - ./:/var/www/html
        depends_on:
            - database

    database:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: database
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - ./db-data:/var/lib/postgresql/data:rw
        ports:
            - '5432'

volumes:
    db-data: