services:
    symfony:
        build:
            context: .
        ports:
            - '8000:80'
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql

    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: symfony
            MYSQL_ROOT_PASSWORD: pass
        ports:
            - '3306:3306'

    pma:
        image: phpmyadmin
        restart: always
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: pass
        ports:
            - '9000:80'